CtrlVET/urls.py
# _*_ coding: utf-8 _*_
"""CtrlVET URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
#Importação da classe TemplateView 
from django.views.generic import TemplateView 
from django.contrib import admin
#from templates import *

"""
Classe generic view que renderiza templates para a prototipagem de interface.
"""
class MockUp(TemplateView):
    """
    Essa função recebe como argumento as variáveis de contexto necessárias para 
    renderizar o template através da url definida em url patterns.
    (override da função da generic view Template View).
    """
    def get_context_data(self, **kwargs):
        self.template_name = self.kwargs["template_name"]
        return super(MockUp,self).get_context_data(**kwargs)

    """
    Para que as urls de templates sejam mapeados como view e com os argumentos 
    passados para a função get_context_data.
    """

# Overrides the default 400 handler django.views.defaults.bad_request
handler400 = 'cadastro.bad_request'
# Overrides the default 403 handler django.views.defaults.permission_denied
handler403 = 'cadastro.views.permission_denied'
# Overrides the default 404 handler django.views.defaults.page_not_found
handler404 = 'cadastro.views.page_not_found'
# Overrides the default 500 handler django.views.defaults.server_error
handler500 = 'cadastro.views.server_error'	
	
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^(?P<template_name>.*)$', MockUp.as_view()),
    url(r'', include('cadastro.urls')),
    url(r'', include('financeiro.urls')),
    url(r'', include('consulta.urls')),
    url(r'', include('login.urls')),
    #url(r'^agenda', agenda.html),
]

financeiro/urls.py
# _*_ coding: utf-8 _*_

from django.conf.urls import url, include
from financeiro.views import *


urlpatterns = [
    #Url sucess
    url(r'^success/$',  SuccessView.as_view(), name='success'),

    #Urls relacionadas às views de Financeiro

    url(r'^pagamentos/resumo$',  PagamentoResumo.as_view(), name='pagamento_resumo'),
    #url(r'^pagamentos/detalhes/(?P<financeiro_id>\d+)/', financeiroDetalhesView.as_view(), name = 'financeiro_detalhes'),
    #url(r'^pagamentos/detalhes/editar/(?P<pk>\d+)/',financeiroEditar.as_view(),  name = 'financeiro_editar'),
    #url(r'^pagamentos/detalhes/deletar/(?P<pk>\d+)/',financeiroDeletar.as_view(),  name = 'financeiro_deletar'),
    url(r'^pagamentos/cadastro$', NotaFormView.as_view(), name = 'nota_cadastro'),
    url(r'^pagamentos/debitos$', ListView.as_view(), name = 'financeiro_debitos'),
    url(r'^pagamentos/recebidos$', RecebidosListView.as_view(), name = 'financeiro_recebidos'),
    #url('^pagamentos/cadastro/debito', DebitoFormView.as_view(), name = 'debito_cadastro'),
    url(r'^pagamentos/relatorio$', AnoList.as_view(), name = 'ano_list'),
    url(r'^pagamentos/relatorio/(?P<ano_id>\d+)/', AnoDetalhesView.as_view(), name = 'ano_detail'),
    url(r'^pagamentos/relatorio/gerarPdf/([0-9][0-9][0-9][0-9])', GeraPdfPrestacaoContas.as_view(), name = 'gerarPdf'),
    url(r'^pagamentos/resumo/gerarPdf/(?P<nota_id>\d+)/', GeraPdfNotaDePagamento.as_view(), name = 'nota_de_pagamento'),
    #Urls relacionadas às views de Estoque
    url(r'^pagamentos/resumo/efetuarpagamento/(?P<pk>\d+)/$',  EfetuarPagamento.as_view(), name='efetuar_pagamento'),
    url(r'^estoque/resumo$',  EstoqueResumo.as_view(), name='estoque_resumo'),
    url(r'^estoque/cadastro$', ItemNotaFormView.as_view(), name = 'item_cadastro'),    
]

login/urls.py
from django.conf.urls import url, include
from login.views import *
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^main/signup/$', signup, name='signup'),
    url(r'^login/$|main/login/^$', auth_views.login,{'template_name': 'login/login.html'}, name='login'),
    url(r'^main/logout/$', auth_views.logout, {'template_name': 'login/logout.html'},name='logout'),
    url(r'^main/veterinario/$', TemplateView.as_view(template_name='veterinario_auth.html')),
    url(r'^main/secretario/$', TemplateView.as_view(template_name='secretario_auth.html')),
    url(r'^main/tecnico/$', TemplateView.as_view(template_name='tecnico_auth.html')),
]

financeiro/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from cadastro.models import AtendimentoAbs 

#DAQUI PRA BAIXO SAO AS CLASSES DE NOTA,DEBITO E ITEMNOTA	

	
class Ano(models.Model):
	_ano = models.CharField(verbose_name='Ano',max_length=4)

	def get_absolute_url(self):
        	return reverse('ano_detail', kwargs={'pk': self.pk})

	def _get_ano(self):
		return self._ano

	def _set_ano(self, ano):
		self._ano = ano

	ano = property(_get_ano,_set_ano)
		
	def __unicode__(self):
		return u'%s' % (self.ano)
	
	def __str__(self):
		return u'%s' % (self.ano)
	
class ItemNotaAbs(models.Model):
	_nome = models.CharField(verbose_name='Nome',max_length=150)
	_valor = models.DecimalField(verbose_name='Valor',max_digits=9, decimal_places=2)
	
	class Meta:
			abstract = True
			
class AcoesItemNota(ItemNotaAbs):
	class Meta:
			abstract = True
	
class ItemNota(AcoesItemNota):

	def _get_nome(self):
		return self._nome		
	
	def _set_nome(self,nome):
		self._nome = nome
		
	def _get_valor(self):
		return self._valor		
	
	def _set_valor(self,valor):
		self._valor = valor

	def __unicode__(self):
		return u'%s - %s (R$)' % (self._nome, self.valor)		
		
	nome = property(_get_nome,_set_nome)	
	valor = property(_get_valor,_set_valor)					

class NotaAbs(models.Model):
	
	SETOR_CHOICES = (
		('1', 'Clínica de Pequenos'),
		('2', 'Clínica de Grandes'),
		('3', 'Clínica Cirúrgica'),
		('4', 'Patologia Clínica'),
		('5', 'Diagnóstico por Imagem'),
		('6', 'Parasitologia'),
		('7', 'Microbiologia'),
		('8', 'Patologia Animal'),
	 )
	
	_data = models.DateField(auto_now_add=True)
	setor = models.CharField(verbose_name='Setor', max_length=30, choices=SETOR_CHOICES)
	atendimento = models.OneToOneField(AtendimentoAbs,on_delete=models.CASCADE,primary_key=True)
	status = models.BooleanField(verbose_name='Pago', default=False)
	ano = models.ForeignKey(Ano, on_delete = models.CASCADE, related_name='notas')
	itemNota = models.ManyToManyField(ItemNota, related_name='notas')

	class Meta:
			abstract = True

	def __unicode__(self):
		return u'%s - %s' % (self.setor, self._data)

	def __str__(self):
		return u'%s - %s' % (self.setor, self._data)

class AcoesNota(NotaAbs):	
	class Meta:
			abstract = True
	
class Nota(AcoesNota):
	
	def get_absolute_url(self):
		return reverse('nota_detail', kwargs={'pk': self.pk})

	def _get_data(self):
		return self._data		
	
	def _set_data(self,data):
		self._data = data

	data = property(_get_data,_set_data)



class Produto(ItemNota):
	pass

class Servico(ItemNota):
	pass

financeiro/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
from django.conf.urls import url

"""Classes de views genericas utilizadas"""
from django.views.generic import View, CreateView, TemplateView, DetailView, UpdateView, DeleteView, ListView, FormView
from django.views.generic.detail import SingleObjectMixin
from _functools import reduce

'HttpResponse para uma pagina template indicando que a operação foi realizada (verificar se tal página existe)'
from django.http import HttpResponseRedirect

'Importando Formularios necessários para views de tutor e animal'
from .forms import *
'Importando Models necessárias para views de tutor e animal'
from cadastro.models import Consulta,Exame

from django.forms.models import model_to_dict #iterar em object no template

'Importando atributos da model a serem utilizados nas buscas'
import operator
from django.db.models import Q

from django.forms.formsets import formset_factory

'Importacao para gerar pdf'
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.pagesizes import landscape
from reportlab.platypus import Image
from django.http import HttpResponse
from datetime import datetime

from django.db.models import Sum


from django_tables2 import MultiTableMixin, SingleTableView, RequestConfig
from .tables import *


class SuccessView(TemplateView):
	template_name='financeiro/success.html'	


class ProdutoFormView(FormView):
	pass

class ServicoFormView(FormView):
	pass


class PrestacaoContasView(TemplateView):
	template_name='financeiro/pagamento_pretacaocontas.html'	


"""class DebitoFormView(FormView):
	template_name = 'financeiro/debito_form.html'
	form_class = DebitoModelForm
	success_url = '/success/'
	debito_formset = formset_factory(NotaModelForm)

	def form_valid(self, form):
		form.save()
		debito_formset.save()
		return HttpResponseRedirect('/success/')

	def get_context_data(self, *args, **kwargs):
		context = super(DebitoFormView, self).get_context_data(*args, **kwargs)
		context['debito_formset'] = formset_factory(NotaModelForm)
		return context 
"""

class NotaFormView(FormView):
	template_name = 'financeiro/nota_form.html'
	form_class = ItemNotaModelForm
	success_url = '/success/'

	def form_valid(self, faorm):
		
		form.save()
		return HttpResponseRedirect('/success/')
		
		
class DebitosList(ListView):
	model = Nota
	paginate_by = 10

class DebitosListView(DebitosList):
	template_name = 'financeiro/debitos_list.html'
	def get_queryset(self):
		return Nota.objects.filter(status=0)

class RecebidosListView(DebitosList):
	template_name = 'financeiro/recebidos_list.html'
	def get_queryset(self):
		return Nota.objects.filter(status=1)		
		

class PagamentoResumo(TemplateView):
	template_name='financeiro/pagamento_resumo.html'
	
	def get_context_data(self, *args, **kwargs):
		context = super(PagamentoResumo, self).get_context_data(*args, **kwargs)
		context['recebidos_list'] = (Nota.objects.filter(status=1).annotate(total=Sum('itemNota___valor'))).order_by('status')[:5]
		context['debitos_list'] = (Nota.objects.filter(status=0).annotate(total=Sum('itemNota___valor'))).order_by('status')[:5]
		return context 



'''class ListPagamento(ListView):
	model = GENERIC_PAGAMENTO
	paginate_by = 10

class EfetuarPagamento(FormView):
	template_name = 'financeiro/GENERICO_PAGAMENTO_FORM.HTML'
	form_class = GENERIC_PAG_FORM
	success_url = '/success/'
	def form_valid(self, form):
		form.save()
		return HttpResponseRedirect('/success/')
  
class AlterarPagamento(UpdateView):
	form_class = GENERIC_PAG_FORM
	model = GENERIC_PAGAMENTO
	fields = '_all_'
	template_name_suffix = '_update_form'
	success_url = '/success/'

class CancelarPagamento(self):
	model = GENERIC_PAGAMENTO
	success_url = reverse_lazy('tutor_resumo')
	success_url = '/successs/'
  
class DetalhesPagamento(DetailView):
	pk_url_kwarg = "generic_id"
	model = GENERIC_PAGAMENTO

	def get_context_data(self, **kwargs):
		context = super(DetalhesPagamento, self).get_context_data(**kwargs)
		return context
	  
class PagamentoBuscaListView(self):
  def get_queryset(self):
	result = super(PagamentoBuscaListView, self).get_queryset()
	query = self.request.GET.get('q')
	if query:
		query_list = query.split()
		result = result.filter(
		reduce(operator.and_,
		(Q(_nome__icontains=q) for q in query_list)) |
		reduce(operator.and_,
		(Q(_email__icontains=q) for q in query_list)) |
		reduce(operator.and_,
		(Q(_cpf__icontains=q) for q in query_list))
		)

		return result'''

class AnoList(ListView):
	model=Ano
	
class AnoDetalhesView(DetailView):
	pk_url_kwarg = "ano_id"
	model = Ano

	def get_context_data(self, **kwargs):
		context = super (AnoDetalhesView, self).get_context_data(**kwargs)

		debitos = self.object.notas.all()
		soma = []
		for debito in debitos:
			soma.append(debito.itemNota.valor)
		context ['valor_total'] = sum(soma)
		soma = []
				
		for debito in debitos:
			if (debito.nota.setor == '1'):
				soma.append(debito.itemNota.valor)
		context ['pequenos'] = sum(soma)
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '2'):
				soma.append(debito.itemNota.valor)
		context ['grandes'] = sum(soma)	
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '3'):
				soma.append(debito.itemNota.valor)
		context ['cirurgica'] = sum(soma)	
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '4'):
				soma.append(debito.itemNota.valor)
		context ['clinica'] = sum(soma)
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '5'):
				soma.append(debito.itemNota.valor)
		context ['imagem'] = sum(soma)
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '6'):
				soma.append(debito.itemNota.valor)
		context ['parasitologia'] = sum(soma)
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '7'):
				soma.append(debito.itemNota.valor)
		context ['microbiologia'] = sum(soma)
		soma = []

		for debito in debitos:
			if (debito.nota.setor == '8'):
				soma.append(debito.itemNota.valor)
		context ['animal'] = sum(soma)
		soma = []

		return context

class GeraPdfPrestacaoContas(DetailView):
	model=Ano

	def get(self, request,ano):
		pk_url_kwarg = "ano_id"
		model = Ano
	
		response = HttpResponse(content_type='application/pdf')
		response['Content-Disposition'] = 'attachment; filename= "Prestacao de contas.pdf"'
		pdf = canvas.Canvas(response)
		pdf.setLineWidth(.2)
		pdf.setFont('Helvetica', 12, leading=None)
		
		pdf.setFont('Helvetica', 16, leading=None)
		pdf.drawString(30,800,'Prestação de Contas''(Jan - Dez) '+str(ano))
		pdf.setFont('Helvetica', 14, leading=None)
		
		coluna = 30
		colunaP = 440
		linha = 750
		espacamento = 35
		
		pdf.drawString(coluna,linha,'Setor')
		pdf.drawString(400,linha,'Valor Arrecadado (R$)')
		pdf.line(coluna,739,540,739)
		pdf.setFont('Helvetica', 12, leading=None)
		notas = Nota.objects.all()
		linha = linha-espacamento
		soma = []
		
		for nota in notas:
			if (nota.setor == '1' and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Clínica de Pequenos')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
		
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '2'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Clínica de Grandes')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
		
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '3'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Clínica Cirúrgica')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))	
			
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '4'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Patologia Clínica')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))	
		
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '5'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Diagnóstico por Imagem')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))	
		
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '6'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Parasitologia')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
			
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '7'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Microbiologia')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
		
		soma = []
		linha = linha-espacamento
		
		for nota in notas:
			if (nota.setor == '8'and nota.ano.ano == ano):
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Patologia Animal')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
		
		soma = []
		linha = linha-espacamento
		
		pdf.line(30,459,540,459)
		
		for nota in notas:
			if nota.ano.ano == ano:
				itens= nota.itemNota.all()
				for item in itens:
					soma.append(item.valor)
		pdf.drawString(coluna,linha,'Valor Total Arrecadado (R$)')
		pdf.drawString(colunaP,linha,"%d,00" % sum(soma))
		dataAtual = datetime.now()
		pdf.drawString(30,30,'Emissão do Relatório: '+str(dataAtual.day)+'/'+str(dataAtual.month)+'/'+str(dataAtual.year))	
		pdf.save()
		return response
		
		
class GeraPdfNotaDePagamento(DetailView):
	model=Nota

	def get(self, request,nota_id):
		pk_url_kwarg = "nota_id"
		model = Nota

		response = HttpResponse(content_type='application/pdf')

financeiro/templates/financeiro/ano_detail.html
{% extends "financeiro/pagamento_resumo.html" %}


{% block breadcrumbs %}
{{ block.super }}
<a href="" class="breadcrumb">Prestação de Contas {{ object.ano }}</a>
{% endblock %}

{% block content %}

	<div class="row">

		<div class="card-content">

			{% block estatisticas %}
			
			{% endblock %}

			{% block lista %}


			<div class="row">
				<div class="col s12 m12 l12">
					<div class="card ">
						<div class="card-content">
							<div class="row">
							<span class="card-title"><a href="#">Prestação de Contas {{ object.ano }} (Jan - Dez)</a></span>
							</div>
							{% if object.debitos.all %}

							<table class="reponsive-table highlight">
								<thead>
									<th data-field="">Setor</th>
									<th data-field="">Valor Arrecadado (R$)</th>
								</tr>
							</thead>

							<tbody>
								<tr>
									<td>Clínica de Pequenos</td>
									<td>{{ pequenos }}</td>
								</tr>
								<tr>
									<td>Clínica de Grandes</td>
									<td>{{ grandes }}</td>
								</tr>
								<tr>
									<td>Clínica Cirúrgica</td>
									<td>{{ cirurgica }}</td>
								</tr>
								<tr>
									<td>Patologia Clínica</td>
									<td>{{ clinica }}</td>
								</tr>
								<tr>
									<td>Diagnóstico por Imagem</td>
									<td>{{ imagem }}</td>
								</tr>
								<tr>
									<td>Parasitologia</td>
									<td>{{ parasitologia }}</td>
								</tr>
								<tr>
									<td>Microbiologia</td>
									<td>{{ microbiologia }}</td>
								</tr>
								<tr>
									<td>Patologia Animal</td>
									<td>{{ animal }}</td>
								</tr>
						
							<thead>
								<th data-field=""></th>
								<th data-field=""></th>
							</tr>
							</thead>
							<tr>
								<td><b>Valor Total Arrecadado (R$)</b></td>
								<td><b> {{ valor_total }} </b></td>
							</tr>
								</tbody>
							</table>
							{% else %}
							<p>Nenhum entrada relatada no ano selecionado.</p>
							{% endif %}

						</div>
					</div>
				</div>

				{% endblock lista %}



			</div>


		<div class="row">
			<div class="col s12 m12 l12">
				<div class="card-content right">
					<button class="btn waves-effect waves-light indigo darken-4" onClick="javascript:history.go(-1);"><i class="material-icons right">arrow_back</i>Voltar</button>
					<a href="{% url 'gerarPdf' object.ano %}" class="btn waves-effect waves-light indigo darken-4 "><i class="material-icons left">add</i>gerarPdf</a>
				</div>	
			</div>
		</div>
	</div>
</div>


	{% endblock %}

financeiro/templates/financeiro/base_form.html
{% extends "financeiro/base_visaogeral.html" %}

{% load material_form %} 

{% block breadcrumbs %}
{{ block.super }}
{% endblock %}


{% block content %}


{% block lista %}
{% endblock %}

{% block form_submit_action %}
{% endblock %}

{% block form %}
{% endblock %}

{% block form_submit %}
{% endblock %}



{% endblock %}

financeiro/templates/financeiro/pagamento_listagem.html
<div class="row">
	<div class="col s12 m12 l12">
		<div class="card">
			<div class="card-content">
				<span class="card-title">A Receber</span>

				{% if debitos_list %}

				<table class="reponsive-table centered highlight">
					<thead>
						<tr>
							<th>Id</th>
							<th class="hide-on-small-only">Data de Atendimento</th>
							<th class="hide-on-med-and-up">Data</th>
							<th class="hide-on-small-only">Setor</th>
							<th >Cliente</th>
							<th>Valor(R$)</th>
							<th></th>
						</tr>
					</thead>
					<tbody>

						{% for nota in debitos_list %}
						<tr>
							<td><b>{{ nota.pk }}</b></td>
							<td>{{ nota.data|date:"SHORT_DATE_FORMAT" }}</td>
							<td>{{ nota.get_setor_display }}</td>
							<td class="hide-on-small-only"><a href="{% url 'tutor_detalhes' nota.atendimento.cliente.pk %}">{{ nota.atendimento.cliente.nome }}</a></td>
							<td>{{ nota.total }}</td>
							<td class="hide-on-small-only"><a class="modal-trigger" href="#reliza_pagamento{{ nota.pk }}"><b>Efetuar Pagamento</b></a></td>
							<td class="hide-on-med-and-up"><a class="modal-trigger btn-floating waves-effect waves-light indigo darken-4" href="#reliza_pagamento{{ nota.pk }}"><i class="material-icons">attach_money</i></a></td>
						</tr>
					</tbody>

					<!-- Modal -->
					<div id="reliza_pagamento{{ nota.pk }}" class="modal">
						<div class="modal-content">
							<h4>Confirmar pagamento</h4>
							<div class="row">
								<div class="col s12 m6 l6">
									<p>Nota: {{ nota.pk }} </p>
									<p>Total: {{ nota.total }}</p>
								</div>
								<div class="col s12 m6 l6">
									<p>Data: {{ nota.data }}</p>
								</div>								
							</div>
						</div>
						<div class="modal-footer">
							<a href="{% url 'efetuar_pagamento' nota.pk %}" class="modal-action modal-close btn waves-effect waves-light indigo darken-4">Confirmar</a>
						</div>
					</div>

					<!-- Modal -->

					{% endfor %}

				</table>

				{% else %}
				<p>Nenhum pagamento <i>a receber</i> encontrado</p>
				{% endif %}
				
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col s12 m12 l12">
		<div class="card">
			<div class="card-content">
				<span class="card-title">Últimos Recebidos</span>

				{% if recebidos_list %}

				<table class="reponsive-table centered highlight">

					<thead>
						<tr>
							<th>Id</th>
							<th>Data de Atendimento</th>
							<th class="hide-on-small-only">Setor</th>
							<th class="hide-on-small-only">Cliente</th>
							<th>Valor(R$)</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						{% for nota in recebidos_list %}
						<tr>
							<td><b>{{ nota.pk }}</b></td>
							<td>{{ nota.data|date:"SHORT_DATE_FORMAT" }}</td>
							<td class="hide-on-small-only">{{ nota.get_setor_display }}</td>
							<td class="hide-on-small-only"><a href="{% url 'tutor_detalhes' nota.atendimento.cliente.pk %}">{{ nota.atendimento.cliente.nome }}</a></td>
							<td>{{ nota.total }}</td>
							<td class="hide-on-small-only"><a href="{% url 'nota_de_pagamento' nota.pk %}"><b>Nota de Pagamento</b></a></td>
							<td class="hide-on-med-and-up"><a class="btn-floating waves-effect waves-light indigo darken-4" href="{% url 'nota_de_pagamento' nota.pk %}"><i class="material-icons">receipt</i></a></td>
						</tr>
						{% endfor %}
					</tbody>

				</table>

				{% else %}
				<p>Nenhum pagamento <i>recebido</i> encontrado</p>
				{% endif %}

			</div>
		</div>
	</div>
</div>



<!-- Modal Trigger -->

financeiro/templates/financeiro/recebidos_list.html
{% extends "financeiro/pagamento_resumo.html" %}

{% block breadcrumbs %}
{{ block.super }}
<a href="{% url 'financeiro_recebidos' %}" class="breadcrumb">Recebidos</a>
{% endblock %}

{% block content %}
<div class="row">
	<div class="card">
		<div class="card-content">

			{% block pesquisa %}
			{{ block.super }}
			{% endblock %}

			{% block lista %}

			<div class="row">
				<div class="col s12 m12 l12">
					<span class="card-title">Débitos</span>
					<div class="divider"></div>
					<div class="row">
						<div class="col s12 m12">

							{% if object_list %}

							<table class="reponsive-table centered highlight">
								<thead>
									<tr>
										<th>Setor</th>
										<th>Data</th>
										<th>Valor(R$)</th>
										<th>Valor Recebido(R$)</th>
									</tr>
								</thead>
								<tbody>

									{% for nota in object_list %}
									<tr>
										<td><a href=""><b>{{ nota.get_setor_display }}</b></a></td>
										<td><a href="">{{ nota.data }}</td>
										<td>{{ nota.itemNota.valor }}</td>
										<td>{{ nota.itemNota.valor }}</td>
									</tr>

									{% endfor %}
								</tbody>
							</table>

							{% else %}

							<p>Nenhum <b>débito</b> encontrado</p>
							
							{% endif %}

						</div>
					</div>
				</div>

				{% endblock %}

				{% block paginacao %}

				{% include "cadastro/paginacao.html" %}

				{% endblock %}


				{% endif %}

			</div>
		</div>
	</div>

	{% endblock %}